name = "primitive_root_families"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PrimitiveRootFamilies"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "PrimitiveRootFamilies"
